#!/usr/bin/env python3
"""PROFILE gate: schema, distributions, missingness, leakage scan, design feasibility.
Reads data/raw/ only; writes work/02_profile/{profile.md,profile.json}."""
import hashlib, json, os
import numpy as np, pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RAW = os.path.join(ROOT, "data/raw/chicago_inspections_weather.parquet")
OUT = os.path.join(ROOT, "work/02_profile")
os.makedirs(OUT, exist_ok=True)
SEED = 20260613

def sha256(p, buf=1 << 20):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(buf), b""):
            h.update(b)
    return h.hexdigest()

df = pd.read_parquet(RAW)
N = len(df)
df["date"] = pd.to_datetime(df["inspection_date"])

WEATHER = ["temperature_2m_max","temperature_2m_min","temperature_2m_mean",
           "apparent_temperature_mean","precipitation_sum","rain_sum","snowfall_sum",
           "precipitation_hours","windspeed_10m_max","windgusts_10m_max"]
UNITS = {**{c:"degC" for c in WEATHER[:4]},
         "precipitation_sum":"mm","rain_sum":"mm","snowfall_sum":"cm",
         "precipitation_hours":"hours","windspeed_10m_max":"km/h","windgusts_10m_max":"km/h"}

prof = {"seed": SEED, "n_rows": N, "sha256_parquet": sha256(RAW),
        "date_range": [str(df['date'].min().date()), str(df['date'].max().date())]}

# ---- schema + missingness ----
schema = []
for c in df.columns:
    if c == "date": continue
    s = df[c]
    schema.append({"name": c, "dtype": str(s.dtype), "unit": UNITS.get(c, ""),
                   "n_missing": int(s.isna().sum()), "pct_missing": round(100*s.isna().mean(),3),
                   "n_unique": int(s.nunique(dropna=True))})
prof["schema"] = schema

# ---- numeric distributions ----
num = {}
for c in WEATHER + ["violation_count","latitude","longitude"]:
    s = pd.to_numeric(df[c], errors="coerce")
    q = s.quantile([0,.01,.05,.25,.5,.75,.95,.99,1]).round(3)
    num[c] = {"mean": round(float(s.mean()),3), "std": round(float(s.std()),3),
              "min": float(q[0]), "p1": float(q[.01]), "p5": float(q[.05]),
              "p25": float(q[.25]), "median": float(q[.5]), "p75": float(q[.75]),
              "p95": float(q[.95]), "p99": float(q[.99]), "max": float(q[1.0]),
              "n_missing": int(s.isna().sum())}
prof["numeric_distributions"] = num

# ---- categorical ----
cat = {}
for c in ["results","results_raw","inspection_type","risk","facility_type"]:
    vc = df[c].value_counts(dropna=False).head(12)
    cat[c] = {str(k): int(v) for k, v in vc.items()}
prof["categorical_top"] = cat

# ---- outcome definition ----
# Substantive inspection outcomes: pass / pass_w_conditions / fail. Others are non-outcomes.
NONOUTCOME = ["out_of_business","no_entry","not_ready","business_not_located"]
res = df["results"].astype(str).str.lower()
substantive = res.isin(["pass","pass_w_conditions","fail"])
fail = (res == "fail")
prof["outcome_definition"] = {
    "outcome": "fail = 1 if results=='fail' else 0, restricted to substantive inspections",
    "substantive_results": ["pass","pass_w_conditions","fail"],
    "dropped_nonoutcome_results": NONOUTCOME,
    "n_substantive": int(substantive.sum()),
    "n_dropped_nonoutcome": int((~substantive).sum()),
    "fail_rate_substantive": round(float(fail[substantive].mean()),4),
    "fail_rate_overall": round(float(fail.mean()),4),
}

# violation_count vs results
vc_by_res = df.groupby(res)["violation_count"].agg(["mean","median","count"]).round(2)
prof["violation_count_by_results"] = {k: {"mean": float(v["mean"]),
        "median": float(v["median"]), "n": int(v["count"])} for k, v in vc_by_res.iterrows()}
prof["violation_count_zero"] = {"pct_zero_overall": round(float((df['violation_count']==0).mean()*100),2),
        "pct_zero_among_pass": round(float((df.loc[res=='pass','violation_count']==0).mean()*100),2),
        "pct_zero_among_fail": round(float((df.loc[res=='fail','violation_count']==0).mean()*100),2)}

# ---- LEAKAGE SCAN ----
leak = []
# violations free text present <-> outcome
vio_present = df["violations"].notna()
leak.append({"variable":"violations","verdict":"LEAKAGE",
    "evidence":f"free-text list of cited violations; present for {round(vio_present.mean()*100,1)}% of rows; "
               f"present in {round(vio_present[fail].mean()*100,1)}% of fails vs {round(vio_present[res=='pass'].mean()*100,1)}% of passes; "
               "mechanically generated by the inspection result.",
    "action":"EXCLUDE from RHS; outcome-derived."})
# results_raw is the same as results
agree = (df["results_raw"].astype(str).str.lower().str.replace(' ','_') == res).mean()
leak.append({"variable":"results_raw","verdict":"LEAKAGE",
    "evidence":f"identical to results in {round(agree*100,1)}% of rows; it IS the outcome.",
    "action":"EXCLUDE; it is the outcome."})
# violation_count strongly tied to outcome
auc_proxy = df.groupby(fail)["violation_count"].mean()
leak.append({"variable":"violation_count","verdict":"OUTCOME / PARTIAL-LEAKAGE",
    "evidence":f"mean violation_count = {auc_proxy.get(True,float('nan')):.1f} for fails vs "
               f"{auc_proxy.get(False,float('nan')):.1f} for non-fails; it is a downstream count of citations, "
               "i.e. an alternative outcome, NOT a covariate.",
    "action":"USE ONLY as an alternative (secondary) outcome, never as a regressor."})
for c in WEATHER:
    leak.append({"variable":c,"verdict":"EXOGENOUS-CANDIDATE",
        "evidence":"daily weather keyed to inspection date; plausibly unrelated to a given establishment's "
                   "latent food-safety conditions; shared by all inspections on the same calendar day.",
        "action":"Eligible RHS / treatment, with seasonality + date controls and day-clustered SE."})
prof["leakage_flags"] = leak

# ---- weather variation: within-day vs across-day ----
g = df.groupby(df["date"].dt.normalize())
insp_per_day = g.size()
# verify weather constant within day
within_day_std = df.groupby(df["date"].dt.normalize())[WEATHER].std(ddof=0).max().max()
prof["weather_variation"] = {
    "unique_weather_days": int(df["date"].dt.normalize().nunique()),
    "inspections_per_day_mean": round(float(insp_per_day.mean()),1),
    "inspections_per_day_median": float(insp_per_day.median()),
    "inspections_per_day_max": int(insp_per_day.max()),
    "max_within_day_weather_std": round(float(within_day_std),6),
    "note": "weather is identical for all inspections sharing a calendar date (within-day std=0) -> "
            "treatment varies only across days; MUST cluster SE by date (effective N = n_days, not n_inspections)."}

# ---- repeat / panel structure ----
# establishment id: use dba_name+address (license number absent). Use address as proxy.
df["estab"] = (df["dba_name"].astype(str).str.upper().str.strip() + "@" +
               df["address"].astype(str).str.upper().str.strip())
est_counts = df["estab"].value_counts()
prof["repeat_structure"] = {
    "n_unique_establishments_dba_address": int(df["estab"].nunique()),
    "pct_inspections_in_repeat_estabs": round(float((est_counts[df['estab']].values>1).mean()*100),1),
    "estabs_with_ge2_inspections": int((est_counts>=2).sum()),
    "estabs_with_ge5_inspections": int((est_counts>=5).sum()),
    "median_inspections_per_estab": float(est_counts.median()),
    "max_inspections_per_estab": int(est_counts.max()),
    "note":"establishment FE feasible: most inspections are in repeatedly-inspected establishments; "
           "within-establishment weather variation across inspection dates identifies a weather effect "
           "net of fixed location/cuisine/management quality."}

# ---- supported designs ----
prof["supported_designs"] = [
  {"design":"Cross-sectional / pooled OLS-LPM (or logit): fail ~ weather + seasonality + zip + facility/risk FE",
   "feasible":True,"identification":"weather-on-inspection-day as-good-as-random conditional on season/date; "
   "exogeneity of weather to latent establishment conditions.","diagnostic":"day-clustered SE; "
   "seasonality robustness (month-of-year & DOY controls); placebo with NEXT-period weather."},
  {"design":"Establishment fixed-effects LPM: within-estab variation in weather across inspection dates",
   "feasible":True,"identification":"compares the SAME establishment inspected on hot vs cold/wet days; "
   "removes all time-invariant confounders.","diagnostic":"two-way (estab + month) FE; cluster by date; "
   "test sensitivity to inspection_type composition."},
  {"design":"Inspector/route-style heat effect on leniency (violation_count as secondary outcome)",
   "feasible":True,"identification":"weather affects inspection stringency/throughput.","diagnostic":"poisson/NB; "
   "same controls; report as secondary."},
  {"design":"RDD on a temperature threshold (e.g. freezing 0C)","feasible":False,
   "identification":"no policy/behavioral discontinuity at a known temperature cutoff; weather is continuous "
   "with no assignment rule.","diagnostic":"n/a — REJECTED, no credible running-variable cutoff."},
  {"design":"DiD","feasible":False,"identification":"no discrete treatment turning on at a date for a "
   "treated subgroup; weather is continuous and universal.","diagnostic":"n/a — REJECTED."},
]

prof["recommended_primary"] = ("Establishment-FE linear probability model of inspection FAIL on inspection-day "
  "temperature (and precipitation), with month FE and SE clustered by calendar date; "
  "pooled LPM with season/zip/facility controls as the headline if FE sample too thin.")

json.dump(prof, open(os.path.join(OUT,"profile.json"),"w"), indent=2, default=str)
print("WROTE profile.json")
for k in ["n_rows","date_range"]: print(k, prof[k])
print("substantive:", prof["outcome_definition"]["n_substantive"],
      "fail_rate:", prof["outcome_definition"]["fail_rate_substantive"])
print("weather:", prof["weather_variation"])
print("repeat:", {k:prof["repeat_structure"][k] for k in
      ["n_unique_establishments_dba_address","estabs_with_ge2_inspections","estabs_with_ge5_inspections"]})
PY = prof
